module.exports = {
    INDENT_VALUE: 2,
    Sizes: {
        BOOL_SIZE: 1,
        CHAR_SIZE: 1,
        SHORT_SIZE: 2,
        INT_SIZE: 4,
        LONG_SIZE: 4,
        INT64_SIZE: 8,
        FLOAT_SIZE: 4,
        DOUBLE_SIZE: 8,
        GLENUM_SIZE: 4
    },
    TypeIds: {
        ID_BYTE_ARRAY: 0,
        ID_UBYTE_ARRAY: 1,
        ID_SHORT_ARRAY: 2,
        ID_USHORT_ARRAY: 3,
        ID_INT_ARRAY: 4,
        ID_UINT_ARRAY: 5,
        ID_FLOAT_ARRAY: 6,
        ID_DOUBLE_ARRAY: 7,
        ID_VEC2B_ARRAY: 8,
        ID_VEC3B_ARRAY: 9,
        ID_VEC4B_ARRAY: 10,
        ID_VEC4UB_ARRAY: 11,
        ID_VEC2S_ARRAY: 12,
        ID_VEC3S_ARRAY: 13,
        ID_VEC4S_ARRAY: 14,
        ID_VEC2_ARRAY: 15,
        ID_VEC3_ARRAY: 16,
        ID_VEC4_ARRAY: 17,
        ID_VEC2D_ARRAY: 18,
        ID_VEC3D_ARRAY: 19,
        ID_VEC4D_ARRAY: 20,
        ID_VEC2UB_ARRAY: 21,
        ID_VEC3UB_ARRAY: 22,
        ID_VEC2US_ARRAY: 23,
        ID_VEC3US_ARRAY: 24,
        ID_VEC4US_ARRAY: 25,

        ID_VEC2I_ARRAY: 26,
        ID_VEC3I_ARRAY: 27,
        ID_VEC4I_ARRAY: 28,
        ID_VEC2UI_ARRAY: 29,
        ID_VEC3UI_ARRAY: 30,
        ID_VEC4UI_ARRAY: 31,

        ID_UINT64_ARRAY: 32,
        ID_INT64_ARRAY: 33,

        ID_DRAWARRAYS: 50,
        ID_DRAWARRAY_LENGTH: 51,
        ID_DRAWELEMENTS_UBYTE: 52,
        ID_DRAWELEMENTS_USHORT: 53,
        ID_DRAWELEMENTS_UINT: 54
    }
};