module.exports = {
    INHERIT_RENDERBIN_DETAILS: 0,
    USE_RENDERBIN_DETAILS: 1,
    OVERRIDE_RENDERBIN_DETAILS: 2,
    PROTECTED_RENDERBIN_DETAILS: 4,
    OVERRIDE_PROTECTED_RENDERBIN_DETAILS: 6
};