module.exports = {
    USE_IMAGE_DATA_FORMAT: 0,
    USE_USER_DEFINED_FORMAT: 1,
    USE_ARB_COMPRESSION: 2,
    USE_S3TC_DXT1_COMPRESSION: 3,
    USE_S3TC_DXT3_COMPRESSION: 4,
    USE_S3TC_DXT5_COMPRESSION: 5,
    USE_PVRTC_2BPP_COMPRESSION: 6,
    USE_PVRTC_4BPP_COMPRESSION: 7,
    USE_ETC_COMPRESSION: 8,
    USE_ETC2_COMPRESSION: 9,
    USE_RGTC1_COMPRESSION: 10,
    USE_RGTC2_COMPRESSION: 11,
    USE_S3TC_DXT1c_COMPRESSION: 12,
    USE_S3TC_DXT1a_COMPRESSION: 13
};